Lab5/Lab5/Models/ErrorViewModel.cs
namespace Lab5.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab5/Lab5/Models/ProfileModel.cs
namespace Lab5.Models
{
    public class ProfileModel
    {
        public string Username { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string ProfileImage { get; set; }
    }
}

Lab5/Lab5/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OAuth;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Auth0.AspNetCore.Authentication;
using Lab5.Models;
using System.Diagnostics;

namespace Lab5.Controllers
{
    public class AccountController : Controller
    {
        private readonly ILogger<AccountController> _logger;

        public AccountController(ILogger<AccountController> logger)
        {
            _logger = logger;
        }

        public async Task Login()
        {
            var authenticationProperties = new LoginAuthenticationPropertiesBuilder()
                .WithRedirectUri(Url.Action("Index", "Home"))
                .Build();

            await HttpContext.ChallengeAsync(Auth0Constants.AuthenticationScheme, authenticationProperties);
        }

        [Authorize]
        public async Task Logout()
        {
            var authenticationProperties = new LogoutAuthenticationPropertiesBuilder()
                .WithRedirectUri(Url.Action("Index", "Home"))
                .Build();

            await HttpContext.SignOutAsync(Auth0Constants.AuthenticationScheme, authenticationProperties);
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }

        [Authorize]
        public IActionResult Profile()
        {
            return View(new ProfileModel()
            {
                Email = User.Identity.Name,
                Username = User.Claims.FirstOrDefault(c => c.Type == "https://claims.example.com/username")?.Value,
                FullName = User.Claims.FirstOrDefault(c => c.Type == "full_name")?.Value,
                PhoneNumber = User.Claims.FirstOrDefault(c => c.Type == "https://claims.example.com/phone_number")?.Value,
                ProfileImage = User.Claims.FirstOrDefault(c => c.Type == "picture")?.Value
            });
        }

        [Authorize]
        public IActionResult Claims()
        {
            return View();
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

Lab5/Lab5/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Lab5.Models;

namespace Lab5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab5/Lab5/Controllers/LabsController.cs
using Microsoft.AspNetCore.Mvc;
using LabsLibrary;
using Microsoft.AspNetCore.Authorization;

namespace Lab5.Controllers
{
    public class LabsController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Lab1()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public string Lab1(string input_file, string output_file)
        {
            return LabsLibrary.Lab1.Run(input_file, output_file);
        }



        [Authorize]
        public IActionResult Lab2()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public string Lab2(string input_file, string output_file)
        {
            return LabsLibrary.Lab2.Run(input_file, output_file);
        }


        [Authorize]
        public IActionResult Lab3()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public string Lab3(string input_file, string output_file)
        {
            return LabsLibrary.Lab3.Run(input_file, output_file);
        }
    }
}

Lab5/Lab5/Views/Home/Index.cshtml
@model Lab5.Models.ProfileModel
@{
    ViewData["Title"] = "Home Page";
}

<div>
    @if (User.Identity.IsAuthenticated)
    {

        <h4>Select:</h4>
        <div class="container">
            <ul class="lab-list">
                <li><a href="@Url.Action("Lab1", "Labs")">Lab 1</a></li>
                <li><a href="@Url.Action("Lab2", "Labs")">Lab 2</a></li>
                <li><a href="@Url.Action("Lab3", "Labs")">Lab 3</a></li>
            </ul>
        </div>


    }
    else
    {
            <h1 class="display-3">Welcome in our web-app</h1>
            <p>To get access to labs you need to Sign In</p>
    }
</div>

Lab5/Lab5/Views/Labs/Lab1.cshtml
@{
    ViewData["Title"] = "Lab 1";
}

<div class="row">
    <div class="col-md-12">
        <div>
            <h2>@ViewData["Title"]</h2>
            <br />
            <p>
                <b>Task:</b>
            </p>
            <pre>
Для доступу до лабораторії НДІ Досліджень Даних Рядків використовуються ключі у вигляді прямокутних карток N×M, в яких вирізані дірки. Ці ключі можна вставляти лише одним способом (тобто не повертати, не перевертати не можна). При цьому дірки мають прямокутну форму. До Васі потрапило два ключі від різних лабораторій. Він вирішив їх накласти один на одного так, щоб фігура, що вийшла, мала максимальну кількість дірок (просвітів). При цьому ключі лежали в тому положенні, в якому їх необхідно вставляти в замок, а Вася не хоче їх повертати. Допоможіть Васі визначити максимальну кількість дірок. При накладенні вважаються ті дірки, нутрощі яких не порожні.
Вхідні дані
Перший рядок вхідного файлу INPUT.TXT містить два цілих числа - 1 ≤ N, M ≤ 109 - довжини сторін ключа. Другий рядок містить єдине ціле число - 1 ≤ K1 ≤ 500 - число дірок у першому ключі. Далі в рядках K1 написано по чотири цілих числа - X1, Y1, X2, Y2 (0 ≤ X1 < X2 ≤ N, 0 ≤ Y1 < Y2 ≤ M) – координати кутів відповідних прямокутних дірок. Дірки у ключі не перетинаються і не торкаються.
Далі слідує опис другого ключа в такому ж форматі.
Вихідні дані
У вихідний файл OUTPUT.TXT виведіть єдине ціле число - максимальну кількість дірок, які може отримати Вася.
            </pre>
            <h2>Input data</h2>
            <form method="POST">
                <br />
                <label>Path to input file:</label>
                <br />
                <input type="text" name="input_file" />
                <br />
                <br />
                <label>Path to output file:</label>
                <br />
                <input type="text" name="output_file" />
                <br />
                <br />
                <input type='submit' value='Execute' />
            </form>
        </div>
    </div>
</div>

Lab5/Lab5/Views/Labs/Lab2.cshtml
@{
    ViewData["Title"] = "Lab 2";
}

<div class="row">
    <div class="col-md-12">
        <div>
            <h2>@ViewData["Title"]</h2>
            <br />
            <p>
                <b>Task:</b>
            </p>
            <pre>
Закінчивши університет, Петя вирішив зайнятися розробкою веб-додатків. Отримавши перше замовлення, Петя вважав за розумне на час виконання замовлення забезпечити себе доступом до Інтернету. Провайдер, з яким Петя уклав контракт, забезпечує доступ до Інтернету лише за допомогою сервіс-карток. Коли Петя прийшов у місцеве поштове відділення за їх покупкою, виявилося, що у продажу є N сервіс-карт.
Кожна сервис-карта характеризується трьома числами Bi, Ei, Si, де Si – вартість карти, а Bi і Ei – це початок і закінчення часу її дії, тобто. сервіс-карта дозволяє отримати доступ до Інтернету в будь-який момент часу t такий, що Bi ≤ t ≤ Ei. Час відраховується від певного фіксованого моменту у минулому.
Петя вирішив, що буде працювати над виконанням замовлення, починаючи з часу B і закінчуючи моментом часу E. Основна проблема полягає в тому, що Петя не багатий, тому він хоче на час виконання замовлення забезпечити себе «стабільним» Інтернетом і витратити на це як можна меншу суму. Будемо говорити, що це безліч сервіс-карт забезпечує Пете «стабільний» Інтернет, якщо для будь-якого моменту часу t, такого, що B ≤ t ≤ E, знайдеться хоча б одна сервіс-картка з даної множини, яка дозволяє отримати доступ до Інтернету цей час.
Ваше завдання полягає в тому, щоб визначити мінімальну суму грошей, необхідну Петі для придбання безлічі карток, які забезпечать йому «стабільний» Інтернет на час виконання замовлення.
Вхідні дані
У першому рядку вхідного файлу INPUT.TXT знаходиться одне число N. У другому рядку два числа B і E, розділені пробілом, де B – момент початку проміжку часу, коли Петя буде працювати над виконанням замовлення, а E – момент закінчення.
Наступні N рядків описують сервіс-картки, i з цих рядків описує i-ю сервіс-карту і містить три числа Bi, Ei і Si, розділені одиночними пробілами.
Обмеження: всі числа натуральні, 1 ≤ N ≤ 105, 1 ≤ Bi < Ei ≤ 109, 1 ≤ B < E ≤ 109, 1 ≤ Si ≤ 20 000. Існує хоча б одна множина карт, яка забезпечує «стабільний» Інтернет на час виконання замовлення
Вихідні дані
Вихідний файл OUTPUT.TXT повинен містити одне число, що дорівнює мінімальній сумі грошей, необхідної Пете для придбання безлічі сервіс-карток, яка забезпечить йому "стабільний" Інтернет на час виконання замовлення.
            </pre>
            <h2>Input data</h2>
            <form method="POST">
                <br />
                <label>Path to input file:</label>
                <br />
                <input type="text" name="input_file" />
                <br />
                <br />
                <label>Path to output file:</label>
                <br />
                <input type="text" name="output_file" />
                <br />
                <br />
                <input type='submit' value='Execute' />
            </form>
        </div>
    </div>
</div>

Lab5/Lab5/Views/Labs/Lab3.cshtml
@{
    ViewData["Title"] = "Lab 3";
}

<div class="row">
    <div class="col-md-12">
        <div>
            <h2>@ViewData["Title"]</h2>
            <br />
            <p>
                <b>Task:</b>
            </p>
            <pre>
Починається зима, але в місті К на дорогах все ще продовжується ремонт. Після того, як чергову дорогу було відремонтовано, департамент транспорту дійшов висновку, що дешевше обслуговувати дороги з одностороннім рухом.
Зараз усі дороги у місті К двосторонні. Дорога складається з двох смуг – зустрічного та попутного напрямку. Потрібно перетворити максимальну кількість доріг на односторонні, залишивши одну із двох смуг так, щоб сполучення між точками міста не порушилося. Це означає, що якщо з точки i можна проїхати до точки j (прямо або через проміжні точки), то після введення одностороннього руху ця можливість має залишитися.
Карта міста задається матрицею суміжності M, заповненої нулями та одиницями. Розмірність матриці N (1 ≤ N ≤ 100) – кількість точок міста. Якщо M[i, j] = 1, то існує смуга для переміщення з точки i до точки j, що не проходить через інші точки, інакше M[i, j] = 0 (M[i, i] = 0 для будь-якого i) . Матриця M симетрична щодо головної діагоналі, тобто. M[i, j] = M[j, i], що означає двосторонню дорогу (смуга зустрічного та попутного напрямку).
Вхідні дані
У першому рядку вхідного файлу INPUT.TXT міститься натуральне число N – розмірність матриці M, наступні N рядків, кожний N символів (нулі або одиниці), розділені пробілами – елементи матриці M.
Вихідні дані
У вихідний файл OUTPUT.TXT виведіть максимально можливу кількість двосторонніх доріг, які можна перетворити на односторонні.
            </pre>
            <h2>Input data</h2>
            <form method="POST">
                <br />
                <label>Path to input file:</label>
                <br />
                <input type="text" name="input_file" />
                <br />
                <br />
                <label>Path to output file:</label>
                <br />
                <input type="text" name="output_file" />
                <br />
                <br />
                <input type='submit' value='Execute' />
            </form>
        </div>
    </div>
</div>

Lab5/Lab5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab5</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Main</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Profile">Profile</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav mr-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Sign Out</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Sign In</a>
                            </li>
                        }
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>